# Generated by Django 4.2.11 on 2024-05-10 11:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("products", "0006_alter_product_and_topic_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "product",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "logo",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("description", wagtail.blocks.CharBlock()),
                                        ("slug", wagtail.blocks.CharBlock()),
                                    ]
                                ),
                            ),
                            ("heading", wagtail.blocks.CharBlock()),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
