# Generated by Django 4.2.11 on 2024-05-16 08:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("products", "0006_alter_product_and_topic_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "search_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("placeholder", wagtail.blocks.CharBlock()),
                                        ("button_text", wagtail.blocks.CharBlock()),
                                    ]
                                ),
                            ),
                            (
                                "product_block",
                                wagtail.blocks.ListBlock(
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("name", wagtail.blocks.ChooserBlock()),
                                            ("blurb", wagtail.blocks.TextBlock()),
                                            (
                                                "icon",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    )
                                ),
                            ),
                            (
                                "featured_article_block",
                                wagtail.blocks.ListBlock(
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("description", wagtail.blocks.TextBlock()),
                                            ("link", wagtail.blocks.ChoiceBlock(choices=[])),
                                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                                        ]
                                    )
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
