# Generated by Django 4.2.11 on 2024-05-10 13:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlisting",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    (
                        "product",
                        wagtail.blocks.StructBlock(
                            [
                                ("logo", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ("title", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.CharBlock()),
                                ("slug", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
