# Generated by Django 4.2.11 on 2024-05-16 08:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlist",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "search_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("placeholder", wagtail.blocks.CharBlock()),
                                ("button_text", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "product_block",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("name", wagtail.blocks.CharBlock()),
                                    ("slug", wagtail.blocks.CharBlock()),
                                    ("blurb", wagtail.blocks.TextBlock()),
                                    (
                                        "icon",
                                        wagtail.images.blocks.ImageChooserBlock(required=False),
                                    ),
                                ]
                            )
                        ),
                    ),
                    (
                        "featured_article_block",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("title", wagtail.blocks.CharBlock()),
                                    ("description", wagtail.blocks.TextBlock()),
                                    ("link", wagtail.blocks.URLBlock()),
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ]
                            )
                        ),
                    ),
                ]
            ),
        ),
    ]
