# Generated by Django 4.2.14 on 2024-08-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_singleproductindexpage_sumoplaceholderpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleproductindexpage",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
            preserve_default=False,
        ),
    ]
