# Generated by Django 4.2.14 on 2024-08-07 12:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_alter_featuredarticle_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleproductindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(max_length=255, required=False),
                                ),
                                (
                                    "placeholder",
                                    wagtail.blocks.CharBlock(max_length=255, required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("link", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("Community", "Community"),
                                            ("Paid", "Paid"),
                                            ("Other", "Other"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("featured_articles", wagtail.blocks.StructBlock([])),
                    (
                        "frequent_topics",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "enabled",
                                    wagtail.blocks.BooleanBlock(default=True, required=False),
                                )
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
