# Generated by Django 4.2.14 on 2024-08-07 13:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_singleproductindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleproductindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(max_length=255, required=False),
                                ),
                                (
                                    "placeholder",
                                    wagtail.blocks.CharBlock(max_length=255, required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("link", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("Community", "Community"),
                                            ("Paid", "Paid"),
                                            ("Other", "Other"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "frequent_topics",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "enabled",
                                    wagtail.blocks.BooleanBlock(default=True, required=False),
                                )
                            ]
                        ),
                    ),
                    (
                        "featured_articles",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "article",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        required=True, target_model="wiki.Document"
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "product_snippet",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "product",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        required=True, target_model="products.Product"
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "document_snippet",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "document",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        required=True, target_model="wiki.Document"
                                    ),
                                )
                            ]
                        ),
                    ),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="FeaturedArticle",
        ),
    ]
