# Generated by Django 5.2.12 on 2026-04-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbforums', '0003_alter_post_created_alter_post_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post_in', to='kbforums.post'),
        ),
    ]
