# Generated by Django 5.2.12 on 2026-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0003_alter_sumotag_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sumotaggeditem',
            index=models.Index(fields=['content_type', 'tag', 'object_id'], name='tags_sumota_content_24a6b0_idx'),
        ),
    ]
