# Generated by Django 5.2.12 on 2026-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0005_add_deployment_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='status',
            new_name='submission_status',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='internal_zd_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='zd_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('solved', 'Solved'), ('closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='zd_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
