# Generated by Django 4.2.7 on 2024-01-22 14:06

from django.db import migrations
from django.contrib.auth.models import User

def delete_is_fxa_migrated_false_users(apps, schema_editor):
    User.objects.filter(profile__is_fxa_migrated=False).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_profile_bio_and_upper_name_idx"),
    ]

    operations = [
        migrations.RunPython(delete_is_fxa_migrated_false_users),
    ]
