# Generated by Django 5.2.13 on 2026-05-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_alter_deactivation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Some HTML supported: &#x3C;abbr title&#x3E; "
                    "&#x3C;blockquote&#x3E; &#x3C;code&#x3E; "
                    "&#x3C;em&#x3E; &#x3C;i&#x3E; &#x3C;li&#x3E; "
                    "&#x3C;ol&#x3E; &#x3C;strong&#x3E; &#x3C;ul&#x3E;."
                ),
                null=True,
                verbose_name="Biography",
            ),
        ),
    ]
